spring:
  application:
    name: config-service
  zipkin:
    base-url: http://zipkin-service-3000:8080
  boot:
    admin:
      client:
        url: http://admin-service-2000:2000
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/xiliangMa/mscloud-config.git
          search-paths: mscloud
          username:
          password:
          skip-ssl-validation: true

server:
  port: 8888

eureka:
  instance:
    hostname: config-service-8888
  client:
    service-url:
      defaultZone: http://eureka-server-7000:7000/eureka/, http://eureka-server-7001:7001/eureka/, http://eureka-server-7002:7002/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS



