spring:
  application:
    name: consumer-service-feign
  zipkin:
    base-url: http://mscloud-zipkin-service:8080
  boot:
    admin:
      client:
        url: http://mscloud-admin-service:2000
        instance:
          management-url: http://mscloud-consumer-feign-service:9001/actuator
          health-url: http://mscloud-consumer-feign-service:9001/actuator/health
          service-url: http://mscloud-consumer-feign-service:9001

server:
  port: 9001

eureka:
  instance:
    hostname: mscloud-consumer-feign-service
  client:
    service-url:
      # k8s
      defaultZone: http://mscloud-eureka-service:7000/eureka/
      # defaultZone: http://eureka-server-7000:7000/eureka/, http://eureka-server-7001:7001/eureka/, http://eureka-server-7002:7002/eureka/

# 开启feign 熔断器
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

