spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:8080
  boot:
    admin:
      client:
        url: http://localhost:2000

server:
  port: 7000

eureka:
  instance:
    hostname: eureka-server-7000
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
