spring:
  application:
    name: provider-service
  zipkin:
    base-url: http://mscloud-zipkin-service:8080
  boot:
    admin:
      client:
        url: http://mscloud-admin-service:2000
        instance:
          management-url: http://mscloud-provider-service:8000/actuator
          health-url: http://mscloud-provider-service:8000/actuator/health
          service-url: http://mscloud-provider-service:8000

server:
  port: 8000

eureka:
  instance:
    hostname: mscloud-provider-service
  client:
    service-url:
      # k8s
      defaultZone: http://mscloud-eureka-service:7000/eureka/
      # defaultZone: http://eureka-server-7000:7000/eureka/, http://eureka-server-7001:7001/eureka/, http://eureka-server-7002:7002/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
