spring:
  application:
    name: zipkin-service
  boot:
    admin:
      client:
        url: http://mscloud-admin-service:2000
        instance:
          management-url: http://mscloud-zipkin-service:3000/actuator
          health-url: http://mscloud-zipkin-service:3000/actuator/health
          service-url: http://mscloud-zipkin-service:3000

server:
  port: 3000

eureka:
  instance:
    hostname: mscloud-zipkin-service
  client:
    service-url:
      # k8s
      defaultZone: http://mscloud-eureka-service:7000/eureka/
      # defaultZone: http://eureka-server-7000:7000/eureka/, http://eureka-server-7001:7001/eureka/, http://eureka-server-7002:7002/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
